@HotelListing.Api_HostAddress = https://localhost:7296

GET {{HotelListing.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{HotelListing.Api_HostAddress}}/api/hotels

###
POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  //Hotel
}   

###

@id=1
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  //Hotel
}

###
